#!/bin/bash

REPO_ROOT_DIR=$(git rev-parse --show-toplevel)

files=$( (git diff --cached --name-only --diff-filter=ACMR | grep -Ei "\.java$") || true)

if [ -n "$files" ]; then

  # run precommit task
  "$REPO_ROOT_DIR/gradlew" format

  # store the last exit code in a variable
  RESULT=$?

  # if error, exit
  if [ $RESULT != 0 ]; then
    exit 1
  fi

  # add formatted files to git
  git add $(echo "$files" | paste -s -d " ")

fi

exit 0
